// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../node_modules/.pnpm/@nuxt+nitro-server@3.21.2_db0@0.3.4_idb-keyval@6.2.2_ioredis@5.10.0_magicast@0.5.2_nuxt_234e0028518d20fc2349296b629ae8e5/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../app/server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}