/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'index': RouteRecordInfo<
      'index',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'compare-sessions': RouteRecordInfo<
      'compare-sessions',
      '/compare/:sessions()',
      { sessions: ParamValue<true> },
      { sessions: ParamValue<false> },
      | never
    >,
    'dock-logs': RouteRecordInfo<
      'dock-logs',
      '/dock/logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dock-self-inspect': RouteRecordInfo<
      'dock-self-inspect',
      '/dock/self-inspect',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dock-settings': RouteRecordInfo<
      'dock-settings',
      '/dock/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dock-terminals': RouteRecordInfo<
      'dock-terminals',
      '/dock/terminals',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'session-session': RouteRecordInfo<
      'session-session',
      '/session/:session()',
      { session: ParamValue<true> },
      { session: ParamValue<false> },
      | 'session-session-assets'
      | 'session-session-chunks'
      | 'session-session-errors'
      | 'session-session-graph'
      | 'session-session-packages'
      | 'session-session-plugins'
    >,
    'session-session-assets': RouteRecordInfo<
      'session-session-assets',
      '/session/:session()/assets',
      { session: ParamValue<true> },
      { session: ParamValue<false> },
      | never
    >,
    'session-session-chunks': RouteRecordInfo<
      'session-session-chunks',
      '/session/:session()/chunks',
      { session: ParamValue<true> },
      { session: ParamValue<false> },
      | never
    >,
    'session-session-errors': RouteRecordInfo<
      'session-session-errors',
      '/session/:session()/errors',
      { session: ParamValue<true> },
      { session: ParamValue<false> },
      | never
    >,
    'session-session-graph': RouteRecordInfo<
      'session-session-graph',
      '/session/:session()/graph',
      { session: ParamValue<true> },
      { session: ParamValue<false> },
      | never
    >,
    'session-session-packages': RouteRecordInfo<
      'session-session-packages',
      '/session/:session()/packages',
      { session: ParamValue<true> },
      { session: ParamValue<false> },
      | never
    >,
    'session-session-plugins': RouteRecordInfo<
      'session-session-plugins',
      '/session/:session()/plugins',
      { session: ParamValue<true> },
      { session: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/app/pages/index.vue': {
      routes:
        | 'index'
      views:
        | never
    }
    'src/app/pages/compare/[sessions]/index.vue': {
      routes:
        | 'compare-sessions'
      views:
        | never
    }
    'src/app/pages/dock/logs.vue': {
      routes:
        | 'dock-logs'
      views:
        | never
    }
    'src/app/pages/dock/self-inspect.vue': {
      routes:
        | 'dock-self-inspect'
      views:
        | never
    }
    'src/app/pages/dock/settings.vue': {
      routes:
        | 'dock-settings'
      views:
        | never
    }
    'src/app/pages/dock/terminals.vue': {
      routes:
        | 'dock-terminals'
      views:
        | never
    }
    'src/app/pages/session/[session].vue': {
      routes:
        | 'session-session'
        | 'session-session-assets'
        | 'session-session-chunks'
        | 'session-session-errors'
        | 'session-session-graph'
        | 'session-session-packages'
        | 'session-session-plugins'
      views:
        | 'default'
    }
    'src/app/pages/session/[session]/assets.vue': {
      routes:
        | 'session-session-assets'
      views:
        | never
    }
    'src/app/pages/session/[session]/chunks.vue': {
      routes:
        | 'session-session-chunks'
      views:
        | never
    }
    'src/app/pages/session/[session]/errors.vue': {
      routes:
        | 'session-session-errors'
      views:
        | never
    }
    'src/app/pages/session/[session]/graph/index.vue': {
      routes:
        | 'session-session-graph'
      views:
        | never
    }
    'src/app/pages/session/[session]/packages.vue': {
      routes:
        | 'session-session-packages'
      views:
        | never
    }
    'src/app/pages/session/[session]/plugins.vue': {
      routes:
        | 'session-session-plugins'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
